FROM ubuntu:trusty
# Entrypoint: Comando por defecto, utiliza CMD como parametro del entrypoint
ENTRYPOINT ["/bin/ping", "-c", "3"]

# Hacer ping a localhost del contenedor
# CMD ["/bin/ping", "-c", "3", "localhost"]
CMD ["localhost"]

